name: Unit/Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '^1.16'

      - name: run test
        run: |
          go test -v -count=1 -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: codecov
        - run: |
          bash <(curl -s https://codecov.io/bash)
